//@ sourceMappingURL=lesson4.map
// Generated by CoffeeScript 1.6.1
(function() {
  var greeting, isGoing, job, multi, name, num, number, obj, one, range, three, two, _ref;

  name = "Anton";

  greeting = "Hello, " + name + "!";

  multi = "This is a greeting:\n\n  " + greeting + "\n";

  console.log(multi);

  number = 123.456;

  isGoing = true;

  isGoing = false;

  isGoing = true;

  isGoing = false;

  range = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  range = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  console.log(range);

  name = "Anton";

  job = "Programmer";

  obj = {
    name: name,
    job: job
  };

  obj = {
    name: name,
    job: job
  };

  obj = {
    name: name,
    obj: obj
  };

  console.log(obj);

  _ref = ["1", "2", "3"], one = _ref[0], two = _ref[1], three = _ref[2];

  console.log(two);

  num = 10;

  console.log(num + 1);

}).call(this);
