//@ sourceMappingURL=lesson11.map
// Generated by CoffeeScript 1.6.1
(function() {
  var BorderCollie, Dog, dog, dog2,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Dog = (function() {

    function Dog(name) {
      this.name = name;
    }

    Dog.prototype.growl = function() {
      return console.log('*growl*');
    };

    return Dog;

  })();

  BorderCollie = (function(_super) {

    __extends(BorderCollie, _super);

    function BorderCollie(name, tricks) {
      this.tricks = tricks != null ? tricks : [];
      BorderCollie.__super__.constructor.call(this, name);
    }

    BorderCollie.prototype.perform = function(trick) {
      return console.log(this.tricks ? "" + this.name + " is " + trick : '*whine*');
    };

    BorderCollie.prototype.growl = function(person) {
      if (person === this.master) {
        return console.log('*bark');
      } else {
        return BorderCollie.__super__.growl.call(this);
      }
    };

    return BorderCollie;

  })(Dog);

  dog = new Dog('Spike');

  console.log(dog.name);

  dog.growl();

  dog2 = new BorderCollie('Oreo', ['playing dead', 'fetching a ball']);

  dog2.master = 'Jeremy';

  console.log(dog2.name);

  dog2.perform('playing dead');

  dog2.perform('catching a frisbee');

  dog2.growl('Jeremy');

  dog2.growl('Jim Button');

}).call(this);
