//@ sourceMappingURL=lesson5.map
// Generated by CoffeeScript 1.6.1
(function() {
  var greet, rand, test,
    __slice = [].slice;

  greet = function(name) {
    name = name || "friend";
    return console.log("Hello " + name + "!");
  };

  greet("Fluttershy");

  greet();

  greet = function(name) {
    if (name == null) {
      name = "friend";
    }
    return "Hello " + name + "!";
  };

  console.log(greet());

  console.log(greet("Fluttershy"));

  test = function() {
    var x, y, z;
    x = arguments[0], y = arguments[1], z = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
    console.log(x);
    console.log(y);
    return console.log(z);
  };

  test("one", "two", "three");

  console.log("=======");

  test("one", "two", "three", "four", "five");

  test = function() {
    var x, y, z, _i;
    x = arguments[0], y = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), z = arguments[_i++];
    console.log(x);
    console.log(y);
    return console.log(z);
  };

  test.apply(null, ["one", "two", "three", "four"]);

  (function(messages) {
    return console.log(messages);
  })("Hello");

  rand = function(max, min) {
    if (max == null) {
      max = 10;
    }
    if (min == null) {
      min = 0;
    }
    return Math.floor(Math.random() * (max - min + 1)) + min;
  };

  console.log(rand());

  console.log(rand(100));

  console.log(rand(60, 50));

}).call(this);
