//@ sourceMappingURL=lesson8.map
// Generated by CoffeeScript 1.6.1
(function() {
  var Hero, arr, hero, i, key, obj, value, _i, _j, _k, _l, _len, _len1, _len2, _len3,
    __hasProp = {}.hasOwnProperty;

  arr = ["Dipper", "Mabel", "Stanford", "Soos", "Wendy", "Waddles"];

  obj = {
    hero1: "Dipper",
    hero2: "Mabel",
    grunkle_stan: "Stanford"
  };

  for (i = _i = 0, _len = arr.length; _i < _len; i = ++_i) {
    hero = arr[i];
    console.log("" + i + ": " + hero);
  }

  console.log("-----");

  for (i = _j = 0, _len1 = arr.length; _j < _len1; i = ++_j) {
    hero = arr[i];
    if (hero.indexOf("W") === 0) {
      console.log("" + i + ": " + hero);
    }
  }

  console.log("-----");

  for (i = _k = 0, _len2 = arr.length; _k < _len2; i = _k += 2) {
    hero = arr[i];
    console.log("" + i + ": " + hero);
  }

  console.log("-----");

  for (_l = 0, _len3 = arr.length; _l < _len3; _l++) {
    hero = arr[_l];
    console.log(hero);
  }

  console.log("-----");

  console.log((function() {
    var _len4, _m, _results;
    _results = [];
    for (_m = 0, _len4 = arr.length; _m < _len4; _m++) {
      hero = arr[_m];
      _results.push(hero);
    }
    return _results;
  })());

  console.log("-----");

  for (key in arr) {
    value = arr[key];
    console.log(key, value);
  }

  console.log("-----");

  Hero = function(name) {
    return this.name = name;
  };

  Hero.prototype.topic = "Main hero";

  obj = new Hero("Dipper");

  for (key in obj) {
    if (!__hasProp.call(obj, key)) continue;
    value = obj[key];
    console.log(key, value);
  }

  console.log("-----");

  i = 0;

  while (arr[i]) {
    console.log(arr[i]);
    i++;
  }

  console.log("-----");

  i = 0;

  while (!(i === arr.length)) {
    console.log(arr[i]);
    i++;
  }

  console.log("-----");

  i = 0;

  while (i !== arr.length) {
    console.log(arr[i]);
    i++;
  }

  console.log("-----");

  i = 0;

  while (true) {
    console.log(arr[i++]);
    if (!(i < arr.length)) {
      break;
    }
  }

}).call(this);
