//@ sourceMappingURL=lesson7.map
// Generated by CoffeeScript 1.6.1
(function() {
  var giveWork, greet, machine, name, person, person1, person2;

  name = "Anton";

  if (name === "Dipper") {
    console.log(name);
  } else if (name === "Anton") {
    console.log("Hi " + name);
  } else {
    console.log("What's your name?");
  }

  if (name === "Dipper") {
    console.log(name);
  } else if (name === "Anton") {
    console.log("Hi " + name);
  } else {
    console.log("What's your name?");
  }

  if (name === "Anton") {
    console.log(name);
  }

  machine = {
    running: false,
    turnOn: function() {
      return this.running = true;
    }
  };

  if (!machine.running) {
    machine.turnOn();
  }

  if (!machine.running) {
    machine.turnOn();
  }

  console.log(machine.running);

  machine = {
    running: false,
    turnOn: function() {
      return this.running = true;
    },
    turnOff: function() {
      return this.running = false;
    }
  };

  if (!machine.running) {
    machine.turnOn();
  } else {
    machine.turnOff();
  }

  console.log(machine.running);

  person = {
    name: "Anton",
    job: "Programmer"
  };

  giveWork = function(person) {
    switch (person.job) {
      case "Programmer":
        return console.log("Here's your code work, " + person.name);
      case "Designer":
        return console.log("Here's your design work, " + person.name);
      default:
        return console.log("Um, do you work here?");
    }
  };

  giveWork(person);

  person1 = {
    name: "Anton",
    relationship: "Friend"
  };

  person2 = {
    name: "Mabel",
    relationship: "Boss"
  };

  greet = function(person) {
    return console.log(person.relationship === "Friend" ? "Hi, " + person.name + "!" : person.relationship === "Boss" ? "Hello, ma'am!" : void 0);
  };

  greet(person1);

  greet(person2);

  greet = function(person) {
    var msg;
    msg = (function() {
      switch (person.relationship) {
        case "Friend":
          return "Hi, " + person.name + "!";
        case "Boss":
          return "Hello, ma'am!";
      }
    })();
    return console.log(msg);
  };

  greet(person1);

  greet(person2);

}).call(this);
